<a href="https://colab.research.google.com/github/blueishfiend692/ASL-to-Speech_RNN/blob/master/EE/EERNNModem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow.keras import layers, models
import pandas
import numpy as np
from sklearn.model_selection import train_test_split

mapping = {'a': [1,0,0,0,0,0,0,0,0],
           'b': [0,1,0,0,0,0,0,0,0],
           'c': [0,0,1,0,0,0,0,0,0],
           'd': [0,0,0,1,0,0,0,0,0],
           'e': [0,0,0,0,1,0,0,0,0],
           'f': [0,0,0,0,0,1,0,0,0],
           'g': [0,0,0,0,0,0,1,0,0],
           'h': [0,0,0,0,0,0,0,1,0],
           'i': [0,0,0,0,0,0,0,0,1]}



data = pandas.read_csv('/content/EEdata.csv')

data
tf.test.gpu_device_name()


'/device:GPU:0'

In [3]:
words = data['word']
y = data['word']

words



y

0      a
1      a
2      a
3      a
4      a
      ..
895    i
896    i
897    i
898    i
899    i
Name: word, Length: 900, dtype: object

In [4]:

x = data.iloc[:,2:]

x

hand[0][0]  hand[0][1]  hand[0][2]  hand[0][3]  hand[0][4]  hand[1][0]  \
0         348.0       221.0      1019.0       619.0      1019.5        99.5   
1         206.5       178.0      1018.0       500.5      1018.0        81.0   
2         829.0      1022.5      1020.0       720.0      1020.5       203.0   
3         127.5        63.0       127.0       277.5      1015.5        50.5   
4          84.5        65.5       170.5       252.0      1015.0        49.5   
..          ...         ...         ...         ...         ...         ...   
895      1014.0       327.0       164.0       334.0      1014.0      1008.0   
896      1014.5       196.0       131.5       374.0      1013.5       617.0   
897      1013.5       205.5       134.5       325.0      1013.5      1008.5   
898      1013.0       134.5       136.0       250.5       928.5      1008.0   
899      1014.5       569.0       138.0       263.5       944.5      1008.5   

     hand[1][1]  hand[1][2]  hand[1][3]  hand[1][4]  ...  hand[60][0]  \
0          81.0       490.5       361.0      1016.5  ...          NaN   
1          74.5       326.0       203.0      1015.5  ...          NaN   
2         214.0      1018.0       591.0      1019.0  ...          NaN   
3          35.0        89.5       125.5      1015.5  ...          NaN   
4          41.0        81.5       129.0      1014.5  ...          NaN   
..          ...         ...         ...         ...  ...          ...   
895        66.5        82.0       111.0       364.5  ...          NaN   
896        41.5       101.0        98.0       198.0  ...          NaN   
897        42.5        99.5        96.0       228.5  ...          NaN   
898        39.5       106.0       102.5       135.0  ...          NaN   
899        44.0        93.0       111.5       147.5  ...          NaN   

     hand[60][1]  hand[60][2]  hand[60][3]  hand[60][4]  hand[61][0]  \
0            NaN          NaN          NaN          NaN          NaN   
1            NaN          NaN          NaN          NaN          NaN   
2            NaN          NaN          NaN          NaN          NaN   
3            NaN          NaN          NaN          NaN          NaN   
4            NaN          NaN          NaN          NaN          NaN   
..           ...          ...          ...          ...          ...   
895          NaN          NaN          NaN          NaN          NaN   
896          NaN          NaN          NaN          NaN          NaN   
897          NaN          NaN          NaN          NaN          NaN   
898          NaN          NaN          NaN          NaN          NaN   
899          NaN          NaN          NaN          NaN          NaN   

     hand[61][1]  hand[61][2]  hand[61][3]  hand[61][4]  
0            NaN          NaN          NaN          NaN  
1            NaN          NaN          NaN          NaN  
2            NaN          NaN          NaN          NaN  
3            NaN          NaN          NaN          NaN  
4            NaN          NaN          NaN          NaN  
..           ...          ...          ...          ...  
895          NaN          NaN          NaN          NaN  
896          NaN          NaN          NaN          NaN  
897          NaN          NaN          NaN          NaN  
898          NaN          NaN          NaN          NaN  
899          NaN          NaN          NaN          NaN  

[900 rows x 310 columns]

In [5]:

data.iloc[:,2:]


hand[0][0]  hand[0][1]  hand[0][2]  hand[0][3]  hand[0][4]  hand[1][0]  \
0         348.0       221.0      1019.0       619.0      1019.5        99.5   
1         206.5       178.0      1018.0       500.5      1018.0        81.0   
2         829.0      1022.5      1020.0       720.0      1020.5       203.0   
3         127.5        63.0       127.0       277.5      1015.5        50.5   
4          84.5        65.5       170.5       252.0      1015.0        49.5   
..          ...         ...         ...         ...         ...         ...   
895      1014.0       327.0       164.0       334.0      1014.0      1008.0   
896      1014.5       196.0       131.5       374.0      1013.5       617.0   
897      1013.5       205.5       134.5       325.0      1013.5      1008.5   
898      1013.0       134.5       136.0       250.5       928.5      1008.0   
899      1014.5       569.0       138.0       263.5       944.5      1008.5   

     hand[1][1]  hand[1][2]  hand[1][3]  hand[1][4]  ...  hand[60][0]  \
0          81.0       490.5       361.0      1016.5  ...          NaN   
1          74.5       326.0       203.0      1015.5  ...          NaN   
2         214.0      1018.0       591.0      1019.0  ...          NaN   
3          35.0        89.5       125.5      1015.5  ...          NaN   
4          41.0        81.5       129.0      1014.5  ...          NaN   
..          ...         ...         ...         ...  ...          ...   
895        66.5        82.0       111.0       364.5  ...          NaN   
896        41.5       101.0        98.0       198.0  ...          NaN   
897        42.5        99.5        96.0       228.5  ...          NaN   
898        39.5       106.0       102.5       135.0  ...          NaN   
899        44.0        93.0       111.5       147.5  ...          NaN   

     hand[60][1]  hand[60][2]  hand[60][3]  hand[60][4]  hand[61][0]  \
0            NaN          NaN          NaN          NaN          NaN   
1            NaN          NaN          NaN          NaN          NaN   
2            NaN          NaN          NaN          NaN          NaN   
3            NaN          NaN          NaN          NaN          NaN   
4            NaN          NaN          NaN          NaN          NaN   
..           ...          ...          ...          ...          ...   
895          NaN          NaN          NaN          NaN          NaN   
896          NaN          NaN          NaN          NaN          NaN   
897          NaN          NaN          NaN          NaN          NaN   
898          NaN          NaN          NaN          NaN          NaN   
899          NaN          NaN          NaN          NaN          NaN   

     hand[61][1]  hand[61][2]  hand[61][3]  hand[61][4]  
0            NaN          NaN          NaN          NaN  
1            NaN          NaN          NaN          NaN  
2            NaN          NaN          NaN          NaN  
3            NaN          NaN          NaN          NaN  
4            NaN          NaN          NaN          NaN  
..           ...          ...          ...          ...  
895          NaN          NaN          NaN          NaN  
896          NaN          NaN          NaN          NaN  
897          NaN          NaN          NaN          NaN  
898          NaN          NaN          NaN          NaN  
899          NaN          NaN          NaN          NaN  

[900 rows x 310 columns]

In [6]:
y = np.concatenate([[mapping[i] for i in y]])
y


array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [7]:
print(y.shape)

(900, 9)


In [8]:
x = x.to_numpy()

In [9]:
x = x[:,:45].reshape(900,5,9)
x.size
x

array([[[ 348. ,  221. , 1019. , ...,   81. ,  490.5,  361. ],
        [1016.5,   45.5,   44.5, ...,   32.5,   34.5,   68.5],
        [ 110.5, 1015.5,   31. , ..., 1015. ,   34.5,   37. ],
        [  74. ,  122. , 1015.5, ...,  208. ,  995.5,  163.5],
        [ 183.5,  732. ,  584.5, ..., 1019.5, 1000.5, 1021.5]],

       [[ 206.5,  178. , 1018. , ...,   74.5,  326. ,  203. ],
        [1015.5,   39.5,   47.5, ...,   31.5,   39.5,   63. ],
        [ 109. , 1014.5,   31. , ..., 1014.5,   32.5,   39. ],
        [  66. ,  129. ,  783. , ...,  174. ,  750. ,   78.5],
        [ 152.5,  236. ,  253.5, ...,  669. ,  696.5, 1018. ]],

       [[ 829. , 1022.5, 1020. , ...,  214. , 1018. ,  591. ],
        [1019. ,   98. ,   98.5, ...,   40.5,   51. ,   96. ],
        [ 127.5,  789. ,   33.5, ...,  912.5,   32. ,   41.5],
        [  69. ,  113.5, 1015. , ...,  119. , 1015. ,   32. ],
        [  40. ,   69.5,  133. , ...,   70.5,  144. , 1014.5]],

       ...,

       [[1013.5,  205.5,  134.5, ...

In [10]:
x = x.transpose(0, 2, 1)
x = np.nan_to_num(x)
x

array([[[ 348. , 1016.5,  110.5,   74. ,  183.5],
        [ 221. ,   45.5, 1015.5,  122. ,  732. ],
        [1019. ,   44.5,   31. , 1015.5,  584.5],
        ...,
        [  81. ,   32.5, 1015. ,  208. , 1019.5],
        [ 490.5,   34.5,   34.5,  995.5, 1000.5],
        [ 361. ,   68.5,   37. ,  163.5, 1021.5]],

       [[ 206.5, 1015.5,  109. ,   66. ,  152.5],
        [ 178. ,   39.5, 1014.5,  129. ,  236. ],
        [1018. ,   47.5,   31. ,  783. ,  253.5],
        ...,
        [  74.5,   31.5, 1014.5,  174. ,  669. ],
        [ 326. ,   39.5,   32.5,  750. ,  696.5],
        [ 203. ,   63. ,   39. ,   78.5, 1018. ]],

       [[ 829. , 1019. ,  127.5,   69. ,   40. ],
        [1022.5,   98. ,  789. ,  113.5,   69.5],
        [1020. ,   98.5,   33.5, 1015. ,  133. ],
        ...,
        [ 214. ,   40.5,  912.5,  119. ,   70.5],
        [1018. ,   51. ,   32. , 1015. ,  144. ],
        [ 591. ,   96. ,   41.5,   32. , 1014.5]],

       ...,

       [[1013.5,  228.5,   91.5,  168.5,  

In [11]:
x.shape


(900, 9, 5)

In [12]:


encoder = models.Sequential([
    layers.SimpleRNN(64, return_sequences=True, input_shape=(None, 5)),
    layers.SimpleRNN(64)
])
encoder.summary()

decoder = models.Sequential([
    layers.Dense(32, activation='relu', input_shape=(64,)),
    layers.Dense(9, activation='softmax')
])
decoder.summary()


autoencoder = models.Sequential([
    encoder,
    decoder
])
autoencoder.summary()
autoencoder.compile(optimizer='adam', loss='mse', metrics=['accuracy'])


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, None, 64)          4480      
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 64)                8256      
                                                                 
Total params: 12736 (49.75 KB)
Trainable params: 12736 (49.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 9)                 297       
                                                                

In [13]:
x.shape

(900, 9, 5)

In [14]:
y.shape

(900, 9)

In [15]:

batch_size = 32
epochs = 1000

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)
autoencoder.fit(x_train, y_train,
                epochs=epochs,
                batch_size=batch_size,
                shuffle=True,
                validation_data=(x_val, y_val))

autoencoder.evaluate(x_val, y_val)

Epoch 1/1000


KeyboardInterrupt: ignored

In [16]:

prediction_array = autoencoder.predict(x[:1])[0]


1/1 [==============================] - 0s 240ms/step


In [17]:
prediction_array

array([9.9930382e-01, 2.3730368e-10, 5.4660620e-04, 1.2091891e-07,
       7.1602371e-05, 4.9346022e-06, 1.5517562e-05, 3.6259509e-05,
       2.1147000e-05], dtype=float32)

In [18]:

min_val = 0
index = -1
for i in range(0,len(prediction_array)):
    if prediction_array[i] > min_val:
        min_val = prediction_array[i]
        index = i

print(prediction_array, "    ", index)

[9.9930382e-01 2.3730368e-10 5.4660620e-04 1.2091891e-07 7.1602371e-05
 4.9346022e-06 1.5517562e-05 3.6259509e-05 2.1147000e-05]      0


In [23]:
autoencoder.predict(x[:1])


1/1 [==============================] - 0s 30ms/step


array([[8.7467182e-01, 2.6363975e-04, 4.9550671e-02, 3.2109339e-03,
        2.8106472e-02, 2.9162439e-03, 3.3222035e-02, 3.4205662e-03,
        4.6376819e-03]], dtype=float32)

In [19]:
autoencoder.save('/content/EETrainedModel32_batchSize.keras')
